export type MeatIngredient = {
  name: string;
  category: "Meat";
  animal: "Beef" | "Lamb" | "Sheep" | "Chicken";
  variety: string;
  cut: string;
  unit: string;
  aliases?: string[];
};

export const meatIngredients: MeatIngredient[] = [
  // Beef
  {
    name: "Boneless Beef",
    category: "Meat",
    animal: "Beef",
    variety: "Boneless Beef/Goru Haddi Chara",
    cut: "Cube",
    unit: "Kg",
    aliases: ["Boneless Beef", "Goru Haddi Chara"],
  },
  {
    name: "Bone on Beef",
    category: "Meat",
    animal: "Beef",
    variety: "Bone on Beef/Goru Haddi Soho",
    cut: "Mixed",
    unit: "Kg",
    aliases: ["Bone on Beef", "Goru Haddi Soho"],
  },
  {
    name: "Beef Brisket",
    category: "Meat",
    animal: "Beef",
    variety: "Beef Brisket/Seenar Mangsh",
    cut: "Ribs with meat",
    unit: "Kg",
    aliases: ["Beef Brisket", "Seenar Mangsh"],
  },
  {
    name: "Beef Short Ribs",
    category: "Meat",
    animal: "Beef",
    variety: "Beef Short Ribs/Jaccob's Ladder/Pajor",
    cut: "Short Ribs with meat",
    unit: "Kg",
    aliases: ["Beef Short Ribs", "Jacob's Ladder", "Pajor"],
  },
  {
    name: "Beef Mince",
    category: "Meat",
    animal: "Beef",
    variety: "Beef Mince/Keema/Kabab Mangsh",
    cut: "Minced Beef",
    unit: "Kg",
    aliases: ["Beef Mince", "Keema", "Kabab Mangsh"],
  },
  {
    name: "Beef Steak",
    category: "Meat",
    animal: "Beef",
    variety: "Beef Steak/Beef Loin",
    cut: "Sliced Beef",
    unit: "Kg",
    aliases: ["Beef Steak", "Beef Loin"],
  },
  {
    name: "Beef Liver",
    category: "Meat",
    animal: "Beef",
    variety: "Beef Liver/Kolija",
    cut: "Whole/Cube",
    unit: "Kg",
    aliases: ["Beef Liver", "Kolija", "Koliza"],
  },
  {
    name: "Beef Brain",
    category: "Meat",
    animal: "Beef",
    variety: "Beef Brain/Mogoz",
    cut: "Whole/Portion",
    unit: "Kg",
    aliases: ["Beef Brain", "Mogoz"],
  },
  {
    name: "Beef Shank",
    category: "Meat",
    animal: "Beef",
    variety: "Beef Shank/Shin/Noli",
    cut: "Cut",
    unit: "Kg",
    aliases: ["Beef Shank", "Beef Shin", "Noli"],
  },

  // Lamb
  {
    name: "Boneless Lamb",
    category: "Meat",
    animal: "Lamb",
    variety: "Boneless Lamb/Lamb Haddi Chara",
    cut: "Cube",
    unit: "Kg",
    aliases: ["Boneless Lamb", "Lamb Haddi Chara"],
  },
  {
    name: "Curry Cut Lamb",
    category: "Meat",
    animal: "Lamb",
    variety: "Curry Cut Lamb/Mixed on the Bone",
    cut: "Mixed",
    unit: "Kg",
    aliases: ["Curry Cut Lamb", "Lamb Mixed on the Bone"],
  },
  {
    name: "Lamb Shoulder",
    category: "Meat",
    animal: "Lamb",
    variety: "Lamb Shoulder/Shoulder Joint",
    cut: "Mixed",
    unit: "Kg",
    aliases: ["Lamb Shoulder", "Shoulder Joint"],
  },
  {
    name: "Lamb Shank",
    category: "Meat",
    animal: "Lamb",
    variety: "Lamb Shank",
    cut: "Short Leg",
    unit: "Kg",
    aliases: ["Lamb Shank"],
  },
  {
    name: "Lamb Leg",
    category: "Meat",
    animal: "Lamb",
    variety: "Lamb Leg",
    cut: "Whole or diced",
    unit: "Kg",
    aliases: ["Lamb Leg"],
  },
  {
    name: "Lamb Neck Fillet",
    category: "Meat",
    animal: "Lamb",
    variety: "Lamb Neck Fillet/Chops",
    cut: "Sliced",
    unit: "Kg",
    aliases: ["Lamb Neck Fillet", "Lamb Chops"],
  },
  {
    name: "Lamb Chops",
    category: "Meat",
    animal: "Lamb",
    variety: "Lamb Chops/Ribs/Chump",
    cut: "Cut",
    unit: "Kg",
    aliases: ["Lamb Chops", "Lamb Ribs", "Lamb Chump"],
  },
  {
    name: "Lamb Mince",
    category: "Meat",
    animal: "Lamb",
    variety: "Lamb Mince/Keema",
    cut: "Minced",
    unit: "Kg",
    aliases: ["Lamb Mince", "Lamb Keema"],
  },
  {
    name: "Lamb Paya",
    category: "Meat",
    animal: "Lamb",
    variety: "Lamb Paya",
    cut: "Shin/Noli",
    unit: "Kg",
    aliases: ["Lamb Paya", "Lamb Shin", "Lamb Noli"],
  },

  // Sheep / Mutton
  {
    name: "Whole Sheep",
    category: "Meat",
    animal: "Sheep",
    variety: "Whole Sheep/Ewe/Veri",
    cut: "15-25 kg",
    unit: "Kg",
    aliases: ["Whole Sheep", "Ewe", "Veri"],
  },
  {
    name: "Half Sheep",
    category: "Meat",
    animal: "Sheep",
    variety: "Half Sheep",
    cut: "15-25 kg",
    unit: "Kg",
    aliases: ["Half Sheep"],
  },
  {
    name: "Whole Sheep",
    category: "Meat",
    animal: "Sheep",
    variety: "Whole Sheep/Ewe/Veri",
    cut: "25-50 kg",
    unit: "Kg",
    aliases: ["Whole Sheep", "Ewe", "Veri"],
  },
  {
    name: "Half Sheep",
    category: "Meat",
    animal: "Sheep",
    variety: "Half Sheep",
    cut: "25-50 kg",
    unit: "Kg",
    aliases: ["Half Sheep"],
  },
  {
    name: "Mutton Sheep Boneless",
    category: "Meat",
    animal: "Sheep",
    variety: "Mutton Sheep",
    cut: "Boneless",
    unit: "Kg",
    aliases: ["Mutton Sheep Boneless", "Boneless Mutton"],
  },
  {
    name: "Mutton Sheep Bone On",
    category: "Meat",
    animal: "Sheep",
    variety: "Mutton Sheep",
    cut: "Bone on",
    unit: "Kg",
    aliases: ["Mutton Sheep Bone On", "Bone on Mutton"],
  },
  {
    name: "Mutton Mince",
    category: "Meat",
    animal: "Sheep",
    variety: "Mutton Mince/Keema",
    cut: "Minced",
    unit: "Kg",
    aliases: ["Mutton Mince", "Mutton Keema"],
  },
  {
    name: "Mutton Ribs",
    category: "Meat",
    animal: "Sheep",
    variety: "Mutton Ribs",
    cut: "Mixed",
    unit: "Kg",
    aliases: ["Mutton Ribs"],
  },
  {
    name: "Mutton Fillet",
    category: "Meat",
    animal: "Sheep",
    variety: "Mutton Fillet/Loin",
    cut: "Cut",
    unit: "Kg",
    aliases: ["Mutton Fillet", "Mutton Loin"],
  },

  // Chicken
  {
    name: "Whole Chicken",
    category: "Meat",
    animal: "Chicken",
    variety: "Whole Chicken/Tandoori Chicken",
    cut: "1000-1200",
    unit: "Kg",
    aliases: ["Whole Chicken", "Tandoori Chicken"],
  },
  {
    name: "Baby Chicken",
    category: "Meat",
    animal: "Chicken",
    variety: "Baby Chicken",
    cut: "400-800",
    unit: "Kg",
    aliases: ["Baby Chicken"],
  },
  {
    name: "Chicken Thighs and Legs",
    category: "Meat",
    animal: "Chicken",
    variety: "Chicken Thighs/Legs",
    cut: "Bone on",
    unit: "Kg",
    aliases: ["Chicken Thighs", "Chicken Legs", "Chicken This/legs"],
  },
  {
    name: "Chicken Wings Whole",
    category: "Meat",
    animal: "Chicken",
    variety: "Chicken Wing/Whole 2 Jointed",
    cut: "Whole 2 Jointed",
    unit: "Kg",
    aliases: ["Chicken Wings Whole", "Whole 2 Jointed Wings"],
  },
  {
    name: "Chicken Wings Single",
    category: "Meat",
    animal: "Chicken",
    variety: "Chicken Wings Single",
    cut: "Single",
    unit: "Kg",
    aliases: ["Chicken Wings Single", "Single Wings"],
  },
  {
    name: "Chicken Drumstick",
    category: "Meat",
    animal: "Chicken",
    variety: "Chicken Drumstick",
    cut: "Drumstick",
    unit: "Kg",
    aliases: ["Chicken Drumstick"],
  },
  {
    name: "Chicken Breast Fillet",
    category: "Meat",
    animal: "Chicken",
    variety: "Chicken Breast/Fillet",
    cut: "Boneless/Skinless",
    unit: "Kg",
    aliases: ["Chicken Breast", "Chicken Fillet"],
  },
  {
    name: "Hard Broiler Chicken",
    category: "Meat",
    animal: "Chicken",
    variety: "Hard Broiler Chicken",
    cut: "Whole",
    unit: "Kg",
    aliases: ["Hard Broiler Chicken"],
  },
  {
    name: "Chicken Liver Mix",
    category: "Meat",
    animal: "Chicken",
    variety: "Chicken Liver/Kidney/Gila/Koliaza",
    cut: "Mixed",
    unit: "Kg",
    aliases: ["Chicken Liver", "Chicken Kidney", "Gila", "Koliaza"],
  },
];