export type SpiceIngredient = {
  name: string;
  category: "Spice";
  grade: string;
  weight: string;
  aliases?: string[];
};

export const spiceIngredients: SpiceIngredient[] = [
  {
    name: "Onion",
    category: "Spice",
    grade: "1 kg bag",
    weight: "Kg",
    aliases: ["Onion", "Peyaj", "Piaj"],
  },
  {
    name: "Onion",
    category: "Spice",
    grade: "2 kg bag",
    weight: "Kg",
    aliases: ["Onion", "Peyaj", "Piaj"],
  },
  {
    name: "Onion",
    category: "Spice",
    grade: "5 kg bag",
    weight: "Kg",
    aliases: ["Onion", "Peyaj", "Piaj"],
  },
  {
    name: "Onion",
    category: "Spice",
    grade: "10 kg bag",
    weight: "Kg",
    aliases: ["Onion", "Peyaj", "Piaj"],
  },
  {
    name: "Onion",
    category: "Spice",
    grade: "20 kg bag",
    weight: "Kg",
    aliases: ["Onion", "Peyaj", "Piaj"],
  },

  {
    name: "Garlic",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Garlic", "Roshun"],
  },
  {
    name: "Ginger",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Ginger", "Ada"],
  },
  {
    name: "Red Chilli",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Red Chilli", "Shukna Morich", "Dry Chilli"],
  },
  {
    name: "Green Chilli",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Green Chilli", "Kacha Morich"],
  },
  {
    name: "Turmeric",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Turmeric", "Holud"],
  },
  {
    name: "Cumin",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Cumin", "Jeera"],
  },
  {
    name: "Coriander",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Coriander", "Dhone", "Dhania"],
  },
  {
    name: "Mustard Seed",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Mustard Seed", "Shorisha"],
  },
  {
    name: "Fenugreek",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Fenugreek", "Methi"],
  },
  {
    name: "Black Pepper",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Black Pepper", "Gol Morich"],
  },
  {
    name: "White Pepper",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["White Pepper"],
  },
  {
    name: "Cinnamon",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Cinnamon", "Darchini"],
  },
  {
    name: "Cardamom",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Cardamom", "Elachi"],
  },
  {
    name: "Clove",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Clove", "Lobongo"],
  },
  {
    name: "Bay Leaf",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Bay Leaf", "Tej Pata"],
  },
  {
    name: "Nutmeg",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Nutmeg", "Jaifol"],
  },
  {
    name: "Mace",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Mace", "Joytri"],
  },
  {
    name: "Poppy Seed",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Poppy Seed", "Posto Dana"],
  },
  {
    name: "Fennel",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Fennel", "Mouri"],
  },
  {
    name: "Ajwain",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Ajwain", "Joan"],
  },
  {
    name: "Nigella Seed",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Nigella Seed", "Kalo Jeera", "Kalonji"],
  },
  {
    name: "Tamarind",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Tamarind", "Tetul"],
  },
  {
    name: "Dry Plum",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Dry Plum", "Aloo Bokhara"],
  },
  {
    name: "Raisin",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Raisin", "Kishmish"],
  },
  {
    name: "Cashew Nut",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Cashew Nut", "Kaju Badam"],
  },
  {
    name: "Almond",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Almond", "Kath Badam"],
  },
  {
    name: "Peanut",
    category: "Spice",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Peanut", "Chinabadam"],
  },

  {
    name: "Onion Paste",
    category: "Spice",
    grade: "Frozen",
    weight: "Kg",
    aliases: ["Onion Paste", "Peyaj Bata"],
  },
  {
    name: "Garlic Paste",
    category: "Spice",
    grade: "Frozen",
    weight: "Kg",
    aliases: ["Garlic Paste", "Roshun Bata"],
  },
  {
    name: "Ginger Paste",
    category: "Spice",
    grade: "Frozen",
    weight: "Kg",
    aliases: ["Ginger Paste", "Ada Bata"],
  },

  {
    name: "Turmeric Powder",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Turmeric Powder", "Holud Gura"],
  },
  {
    name: "Red Chilli Powder",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Red Chilli Powder", "Morich Gura"],
  },
  {
    name: "Cumin Powder",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Cumin Powder", "Jeera Gura"],
  },
  {
    name: "Coriander Powder",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Coriander Powder", "Dhone Gura", "Dhania Powder"],
  },
  {
    name: "Black Pepper Powder",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Black Pepper Powder", "Gol Morich Gura"],
  },
  {
    name: "White Pepper Powder",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["White Pepper Powder"],
  },

  {
    name: "Garam Masala",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Garam Masala"],
  },
  {
    name: "Meat Curry Powder",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Meat Curry Powder", "Meat Masala"],
  },
  {
    name: "Fish Curry Powder",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Fish Curry Powder", "Fish Masala"],
  },
  {
    name: "Biriyani Masala",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Biriyani Masala", "Biryani Masala"],
  },
  {
    name: "Roast Masala",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Roast Masala"],
  },
  {
    name: "Jhal Fry Masala",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Jhal Fry Masala"],
  },
  {
    name: "Chat Masala",
    category: "Spice",
    grade: "Powder",
    weight: "Kg",
    aliases: ["Chat Masala", "Chaat Masala"],
  },
];