export type VegetableIngredient = {
  name: string;
  category: "Vegetable";
  grade: string;
  weight: string;
  aliases?: string[];
};

export const vegetableIngredients: VegetableIngredient[] = [
  {
    name: "Potato",
    category: "Vegetable",
    grade: "1 kg bag",
    weight: "Kg",
    aliases: ["Potato", "Aloo"],
  },
  {
    name: "Potato",
    category: "Vegetable",
    grade: "2 kg bag",
    weight: "Kg",
    aliases: ["Potato", "Aloo"],
  },
  {
    name: "Potato",
    category: "Vegetable",
    grade: "5 kg bag",
    weight: "Kg",
    aliases: ["Potato", "Aloo"],
  },
  {
    name: "Potato",
    category: "Vegetable",
    grade: "10 kg bag",
    weight: "Kg",
    aliases: ["Potato", "Aloo"],
  },
  {
    name: "Potato",
    category: "Vegetable",
    grade: "20 kg bag",
    weight: "Kg",
    aliases: ["Potato", "Aloo"],
  },

  {
    name: "Carrot",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Carrot", "Gajor", "Gazor"],
  },
  {
    name: "Cucumber",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Cucumber", "Shosha"],
  },
  {
    name: "Coriander Leaves",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Coriander Leaves", "Dhone Pata"],
  },
  {
    name: "Chichinga",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Chichinga", "Kohi"],
  },
  {
    name: "Broad Bean",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Broad Bean", "Seem", "Uri"],
  },
  {
    name: "Long Bean",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Long Bean", "Borboti", "Luibba"],
  },
  {
    name: "Jhinga",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Jhinga", "Ridge Gourd"],
  },
  {
    name: "Satkora",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Satkora"],
  },
  {
    name: "Jara Lebu",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Jara Lebu"],
  },
  {
    name: "Lemon",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Lemon", "Lebu"],
  },
  {
    name: "Mukhi Kachu",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Mukhi Kachu"],
  },
  {
    name: "Loti",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Loti", "Kochur Loti"],
  },
  {
    name: "Lau",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Lau", "Kadu", "Bottle Gourd"],
  },
  {
    name: "Pumpkin",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Pumpkin", "Kumra"],
  },
  {
    name: "Jali Kumra",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Jali Kumra", "Ash Gourd"],
  },
  {
    name: "Dhundul",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Dhundul"],
  },
  {
    name: "Green Papaya",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Green Papaya", "Kacha Pepe"],
  },
  {
    name: "Green Banana",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Green Banana", "Kacha Kola"],
  },
  {
    name: "Pat Shak",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Pat Shak", "Jute Leaves"],
  },
  {
    name: "Lal Shak",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Lal Shak", "Red Amaranth"],
  },
  {
    name: "Kolmi Shak",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Kolmi Shak", "Water Spinach"],
  },
  {
    name: "Data Shak",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Data Shak"],
  },
  {
    name: "Parsley",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Parsley", "Parsely"],
  },
  {
    name: "Cauliflower",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Cauliflower", "Ful Kopi", "Fulkopi"],
  },
  {
    name: "Cabbage",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Cabbage", "Badha Kopi", "Badhakopi"],
  },
  {
    name: "Broccoli",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Broccoli"],
  },
  {
    name: "Lettuce",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Lettuce", "Iceberg"],
  },
  {
    name: "Salad Onion",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Salad Onion", "Spring Onion"],
  },
  {
    name: "Aubergine",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Aubergine", "Begun", "Eggplant"],
  },
  {
    name: "Tomato",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Tomato"],
  },
  {
    name: "Green Chilli",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Green Chilli", "Kacha Morich"],
  },
  {
    name: "Ol Kopi",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Ol Kopi", "Kohlrabi"],
  },
  {
    name: "Betel Leaf",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Betel Leaf", "Pan"],
  },
  {
    name: "Betel Nut",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Betel Nut", "Supari"],
  },
  {
    name: "Mint Leaf",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Mint Leaf", "Pudina Pata", "Pudina"],
  },
  {
    name: "Capsicum",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Capsicum", "Bell Pepper"],
  },
  {
    name: "Jalapeno",
    category: "Vegetable",
    grade: "Kg",
    weight: "Kg",
    aliases: ["Jalapeno", "Gelapino"],
  },
];