import type {
  Restaurant,
  MenuCategory,
  MenuItem,
  RestaurantLanguageSettings,
} from "@/lib/restaurantMenuTypes";

export const restaurantsSample: Restaurant[] = [
  {
    id: "r1",
    name: "Brick Lane Royal Biryani & Curry",
    slug: "brick-lane-biryani-house",
    area: "brick_lane",
    hubLabel: "Brick Lane",
    cuisine: "bangladeshi",
    address: "Brick Lane, London",
    hasWebsite: true,
    websiteUrl: "https://example.com",
    serviceMode: "both",
    isActive: true,
  },
  {
    id: "r2",
    name: "Green Street Bangladeshi/Indian Savoury",
    slug: "green-street-grill",
    area: "green_street_plashet",
    hubLabel: "Green Street / Plashet Road",
    cuisine: "indian",
    address: "Green Street, London",
    hasWebsite: false,
    serviceMode: "takeaway",
    isActive: true,
  },
  {
    id: "r3",
    name: "Shoreditch Boxpark Kitchen",
    slug: "boxpark-shoreditch-kitchen",
    area: "bethnal_green_road",
    hubLabel: "Bethnal Green Road / Boxpark Shoreditch",
    cuisine: "mixed",
    address: "Bethnal Green Road, London",
    hasWebsite: false,
    serviceMode: "both",
    isActive: true,
  },
];

export const menuCategoriesSample: MenuCategory[] = [
  {
    id: "c1",
    restaurantId: "r1",
    name_en: "Biryani",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "c2",
    restaurantId: "r1",
    name_en: "Curry",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "c3",
    restaurantId: "r2",
    name_en: "Grill",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "c4",
    restaurantId: "r3",
    name_en: "Street Food",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "c5",
    restaurantId: "r3",
    name_en: "Italian Specials",
    sortOrder: 2,
    isActive: true,
  },
];

export const menuItemsSample: MenuItem[] = [
  {
    id: "m1",
    restaurantId: "r1",
    categoryId: "c1",
    name_en: "Chicken Biryani",
    name_fr: "Biryani de poulet",
    name_it: "Biryani di pollo",
    name_es: "Biryani de pollo",
    name_de: "Hähnchen-Biryani",
    description_en: "Classic fragrant rice with chicken and spices.",
    priceMode: "single",
    price: 9.99,
    isPopular: true,
    isActive: true,
  },
  {
    id: "m2",
    restaurantId: "r1",
    categoryId: "c2",
    name_en: "Beef Curry",
    description_en: "Slow-cooked beef curry with traditional spices.",
    priceMode: "separate",
    eatInPrice: 11.99,
    takeawayPrice: 10.99,
    isPopular: true,
    isActive: true,
  },
  {
    id: "m3",
    restaurantId: "r2",
    categoryId: "c3",
    name_en: "Chicken Tikka",
    description_en: "Chargrilled chicken tikka pieces.",
    priceMode: "single",
    price: 8.5,
    isPopular: true,
    isActive: true,
  },
  {
    id: "m4",
    restaurantId: "r3",
    categoryId: "c4",
    name_en: "Lamb Wrap",
    description_en: "Street-style lamb wrap.",
    priceMode: "single",
    price: 7.5,
    isPopular: true,
    isActive: true,
  },
  {
    id: "m5",
    restaurantId: "r3",
    categoryId: "c5",
    name_en: "Margherita Pizza Slice",
    name_it: "Fetta di pizza Margherita",
    description_en: "Simple tomato, mozzarella and basil slice.",
    priceMode: "single",
    price: 4.5,
    isPopular: false,
    isActive: true,
  },
];

export const restaurantLanguageSettingsSample: RestaurantLanguageSettings[] = [
  {
    restaurantId: "r1",
    enableFrench: true,
    enableItalian: true,
    enableSpanish: true,
    enableGerman: true,
  },
  {
    restaurantId: "r2",
    enableFrench: false,
    enableItalian: false,
    enableSpanish: false,
    enableGerman: false,
  },
  {
    restaurantId: "r3",
    enableFrench: true,
    enableItalian: true,
    enableSpanish: false,
    enableGerman: false,
  },
];